# -*- coding: utf-8 -*-
"""Blog articles (/blog/<slug>/). Edit texts here, then run: sh tools/build.sh
Block types in 'body':
  ('h2', 'Nadpis')            – section heading (goes to the table of contents)
  ('h3', 'Podnadpis')
  ('p', 'text s <a href="sluzby/seo/">odkazy</a>')   – links are root-relative, the generator fixes them
  ('ul', ['položka', ...])   ('ol', ['krok', ...])   ('check', ['položka se zatržítkem', ...])
  ('tip', 'Titulek', 'text')  – highlighted box
  ('table', ['sloupec', ...], [['buňka', ...], ...])
  ('cta',)                    – inline "návrh zdarma" banner
"""

DATE = '2026-09-25'

CATS = {
    'ceny': 'Ceny a plánování',
    'seo': 'SEO',
    'geo': 'GEO a AI',
    'gdpr': 'GDPR a právo',
    'obsah': 'Obsah a konverze',
}

ARTICLES = [
  # ------------------------------------------------------------------
  {
    'slug': 'kolik-stoji-webove-stranky',
    'cat': 'ceny', 'obj': 'coin', 'variant': 'bnv-lime', 'read': 8,
    'title': 'Kolik stojí webové stránky v roce 2026? Ceny a na čem záleží',
    'desc': 'Orientační ceny webových stránek v roce 2026: od stavebnice přes šablonu po web na míru. Co ovlivňuje cenu, jaké jsou provozní náklady a jak porovnat nabídky.',
    'h1': 'Kolik stojí webové stránky <span class="serif">v roce 2026?</span>',
    'lead': 'Ceny webů se liší klidně desetinásobně. Vysvětlíme, za co se platí, jaké jsou orientační částky na českém trhu a jak poznat, která nabídka dává smysl právě pro vás.',
    'answer': 'Jednoduchý web na stavebnici vyjde na stovky korun měsíčně plus vaši práci. Web na šabloně od freelancera se obvykle pohybuje kolem 10–30 tisíc Kč, firemní web na míru zhruba 30–100 tisíc Kč a e-shop nebo rozsáhlejší web na míru od 80 tisíc Kč výš. Rozhoduje rozsah, design, texty, funkce a to, kolik práce se odvede na SEO a obsahu.',
    'takeaways': ['Cena závisí hlavně na rozsahu, designu a funkcích', 'Počítejte i s provozem: doména, hosting, správa', 'Porovnávejte nabídky podle toho, co přesně obsahují'],
    'body': [
      ('h2', 'Orientační ceny webových stránek'),
      ('p', 'Čísla níže jsou orientační rozpětí, se kterými se na českém trhu běžně setkáte. Každá nabídka se ale liší tím, co přesně obsahuje, takže je berte jako mapu, ne jako ceník.'),
      ('table', ['Typ webu', 'Orientační cena', 'Pro koho se hodí'], [
        ['Stavebnice (Webnode, Wix apod.)', '0–600 Kč měsíčně + vaše práce', 'Začínající živnostníci, jednoduchá vizitka'],
        ['Web na šabloně (např. WordPress)', 'cca 10–30 tis. Kč', 'Menší firmy s běžnými požadavky'],
        ['Firemní web na míru (5–10 stránek)', 'cca 30–100 tis. Kč', 'Firmy, které chtějí web jako nástroj na poptávky'],
        ['E-shop nebo rozsáhlý web na míru', 'od 80 tis. Kč výš', 'Online prodej, rezervace, registrace, více jazyků'],
      ]),
      ('p', 'Levnější řešení nejsou automaticky špatná a dražší nejsou automaticky lepší. Důležité je, jestli web dokáže to, co od něj potřebujete: aby vás lidé našli, pochopili, co nabízíte, a snadno se ozvali.'),
      ('h2', 'Co nejvíc ovlivňuje cenu webu'),
      ('h3', 'Rozsah a struktura'),
      ('p', 'Jednostránková prezentace je jiná práce než web s deseti podstránkami služeb, referencemi a blogem. Každá stránka znamená návrh, texty, obrázky a ladění pro mobil.'),
      ('h3', 'Design na míru, nebo šablona'),
      ('p', 'Šablona je rychlá a levná, ale váš web pak vypadá podobně jako stovky dalších. Design na míru vychází z vaší firmy a zákazníků a každá sekce má svůj účel. Podrobně to srovnáváme v článku <a href="blog/web-na-miru-nebo-sablona/">Web na míru, nebo šablona</a>.'),
      ('h3', 'Texty a fotografie'),
      ('p', 'Kvalitní texty často rozhodují víc než grafika. Pokud je nemáte, započítejte copywriting. Stejně tak fotografie: vlastní fotky působí důvěryhodněji než fotobanka.'),
      ('h3', 'Funkce'),
      ('ul', ['online rezervace a kalendář', 'platby a e-shop', 'registrace na akce', 'napojení na CRM, účetnictví nebo sklad', 'více jazykových verzí']),
      ('p', 'Každá funkce přidává práci na vývoji i testování. U e-shopů navíc napojení na platební bránu, dopravce a fakturaci.'),
      ('h3', 'SEO, GEO a právní náležitosti'),
      ('p', 'Technické SEO, strukturovaná data, rychlost a příprava na AI vyhledávání by dnes měly být samozřejmostí. Stejně tak cookie lišta a zásady ochrany osobních údajů. Když v nabídce chybí, doplácíte je později.'),
      ('cta',),
      ('h2', 'Provozní náklady, na které se zapomíná'),
      ('p', 'Cena za vytvoření webu je jednorázová, ale web má i průběžné náklady:'),
      ('check', ['doména: obvykle stovky korun ročně', 'hosting: od nuly u statických webů po stovky korun měsíčně u e-shopů', 'správa a aktualizace: podle dohody, často paušál', 'placené pluginy nebo licence u šablon', 'úpravy obsahu, pokud si je neděláte sami']),
      ('tip', 'Tip', 'Zeptejte se dodavatele, komu bude patřit doména, přístupy a zdrojové soubory. Web by měl být váš, ne závislý na jedné osobě.'),
      ('h2', 'Jak porovnat nabídky'),
      ('ol', [
        'Ujasněte si cíl webu: poptávky, prodej, rezervace, nebo jen vizitka.',
        'Nechte si rozepsat, co přesně nabídka obsahuje: počet stránek, texty, SEO, GDPR, úpravy.',
        'Zeptejte se, kolik kol úprav je v ceně a co se účtuje navíc.',
        'Prohlédněte si realizace dodavatele a proklikejte je na mobilu.',
        'Porovnávejte celkové náklady na 2–3 roky, ne jen jednorázovou cenu.',
      ]),
      ('p', 'Nejspolehlivější je vidět konkrétní návrh ještě před objednávkou. Proto u nás dostanete <a href="sluzby/tvorba-webu/">návrh nového webu zdarma do 48 hodin</a> a cenu realizace znáte předem.'),
    ],
    'faq': [
      ('Kolik stojí jednoduchý web pro živnostníka?', 'Jednoduchá prezentace na stavebnici vyjde na stovky korun měsíčně plus vaši práci. Jednoduchý web od profesionála na šabloně se obvykle pohybuje v jednotkách až nízkých desítkách tisíc korun.'),
      ('Proč se ceny webů tak liší?', 'Liší se rozsah práce: design na míru oproti šabloně, texty, fotografie, funkce, SEO a péče po spuštění. Dvě nabídky se stejnou cenou mohou obsahovat úplně jinou práci.'),
      ('Kolik stojí provoz webu měsíčně?', 'Doména stojí obvykle stovky korun ročně, hosting od nuly po stovky korun měsíčně. K tomu případná správa a aktualizace podle dohody s dodavatelem.'),
      ('Vyplatí se web zadarmo?', 'Na úplný začátek může stačit. Pokud má ale web přivádět zákazníky, obvykle narazíte na omezení v designu, rychlosti, SEO a vlastnictví webu.'),
    ],
    'services': ['tvorba-webu', 'eshopy'],
  },
  # ------------------------------------------------------------------
  {
    'slug': 'redesign-webu-bez-ztraty-pozic',
    'cat': 'seo', 'obj': 'spark', 'variant': 'bnv-blue', 'read': 7,
    'title': 'Redesign webu bez ztráty pozic v Googlu: postup',
    'desc': 'Kdy je čas na redesign webu a jak ho udělat, abyste nepřišli o pozice ve vyhledávání. Přesměrování, obsah, Search Console a kontrola po spuštění.',
    'h1': 'Redesign webu <span class="serif">bez ztráty pozic.</span>',
    'lead': 'Nový web má přinést víc zákazníků, ne propad návštěvnosti. Ukážeme, kdy se redesign vyplatí a na co si dát pozor, aby Google nový web přijal bez problémů.',
    'answer': 'Při redesignu nepřijdete o pozice, když zachováte obsah, který se ve vyhledávání daří, nastavíte trvalá přesměrování (301) ze všech starých adres na nové, přenesete titulky a popisky stránek, odešlete novou sitemapu do Google Search Console a po spuštění hlídáte chyby 404 a vývoj návštěvnosti.',
    'takeaways': ['Každá stará adresa musí vést na novou (301)', 'Obsah, který přivádí návštěvníky, nemažte', 'Po spuštění sledujte Search Console'],
    'body': [
      ('h2', 'Kdy je čas na redesign'),
      ('check', ['web se špatně ovládá na mobilu', 'z webu nechodí poptávky ani telefonáty', 'vzhled neodpovídá kvalitě vašich služeb', 'stránky se načítají pomalu', 'chybí cookie lišta nebo zásady ochrany osobních údajů', 'obsah je zastaralý a nikdo ho neaktualizuje']),
      ('p', 'Stačí dva až tři body a redesign se obvykle vyplatí. Zastaralý web odrazuje návštěvníky dřív, než si přečtou, co nabízíte.'),
      ('h2', 'Proč weby po redesignu padají ve vyhledávání'),
      ('p', 'Google zná váš web podle konkrétních adres a obsahu. Když se adresy změní bez přesměrování, staré odkazy vedou do prázdna a hodnota, kterou stránky roky budovaly, se ztratí. Druhou častou chybou je smazání textů, které přiváděly návštěvníky, jen proto, že se nehodily do nového designu.'),
      ('h2', 'Postup redesignu krok za krokem'),
      ('h3', '1. Zmapujte současný web'),
      ('p', 'Sepište všechny adresy starého webu. Pomůže sitemap, Google Search Console nebo nástroj na procházení webu. V Search Console si uložte i stránky a dotazy, které přinášejí nejvíc návštěv.'),
      ('h3', '2. Rozhodněte, co zůstane'),
      ('p', 'Obsah, který se ve vyhledávání daří, zachovejte a vylepšete. Slabé stránky můžete sloučit, ale vždy s přesměrováním na nejbližší obsah.'),
      ('h3', '3. Připravte mapu přesměrování'),
      ('p', 'Ke každé staré adrese přiřaďte novou a nastavte trvalé přesměrování 301. Nepřesměrovávejte vše hromadně na úvodní stránku, to Google vnímá skoro jako smazání.'),
      ('h3', '4. Přeneste SEO základy'),
      ('ul', ['titulky a popisky stránek (title, meta description)', 'nadpisy a klíčová slova, pod kterými vás lidé hledají', 'alternativní texty obrázků', 'strukturovaná data', 'interní odkazy mezi stránkami']),
      ('cta',),
      ('h3', '5. Otestujte před spuštěním'),
      ('p', 'Zkontrolujte rychlost, zobrazení na mobilu, funkčnost formulářů a to, že testovací verze není indexovaná, ale ostrá verze ano.'),
      ('h3', '6. Spusťte a sledujte'),
      ('p', 'Po spuštění odešlete novou sitemapu do Google Search Console a Seznam Webmaster, hlídejte chyby 404 a porovnávejte návštěvnost. Mírné výkyvy v prvních týdnech jsou běžné. Pokud je redesign udělaný správně, pozice se srovnají a díky rychlejšímu a přehlednějšímu webu často rostou.'),
      ('tip', 'Tip', 'Nemažte starý web hned po spuštění nového. Nechte si zálohu obsahu i seznam adres, ať máte z čeho vycházet při kontrole.'),
      ('h2', 'Jak redesign děláme u nás'),
      ('p', 'Nejdřív projdeme váš současný web a zachováme to, co funguje. Do 48 hodin máte <a href="sluzby/redesign-webu/">návrh nové podoby zdarma</a>. Po schválení web postavíme, přesměrujeme staré adresy a spustíme ho bez výpadku. Podívejte se na <a href="realizace.html">skutečné weby našich klientů předtím a teď</a>.'),
    ],
    'faq': [
      ('Přijdu redesignem o pozice v Googlu?', 'Ne, pokud zachováte obsah, který se ve vyhledávání daří, a nastavíte přesměrování 301 ze starých adres na nové. Krátkodobé výkyvy jsou běžné, dlouhodobě se pozice díky lepšímu webu obvykle zlepší.'),
      ('Jak dlouho trvá, než se pozice po redesignu ustálí?', 'Obvykle několik týdnů. Záleží na velikosti webu a na tom, jak rychle Google projde nové adresy. Pomůže odeslání sitemapy v Google Search Console.'),
      ('Musím při redesignu měnit adresy stránek?', 'Nemusíte. Pokud jsou současné adresy srozumitelné, je nejjednodušší je zachovat. Když je měníte, nastavte přesměrování 301.'),
    ],
    'services': ['redesign-webu', 'seo'],
  },
  # ------------------------------------------------------------------
  {
    'slug': 'geo-optimalizace-pro-ai-vyhledavani',
    'cat': 'geo', 'obj': 'bubble', 'variant': 'bnv-dark', 'read': 8,
    'title': 'GEO: jak se dostat do odpovědí ChatGPT a AI vyhledávání',
    'desc': 'Co je GEO (optimalizace pro AI vyhledávání), jak si AI asistenti vybírají zdroje a co udělat, aby doporučili právě vaši firmu. Praktický postup pro firemní weby.',
    'h1': 'Jak se dostat do odpovědí <span class="serif">ChatGPT a spol.</span>',
    'lead': 'Lidé se čím dál častěji neptají Googlu, ale umělé inteligence. Vysvětlíme, co je GEO, jak AI asistenti vybírají firmy, které doporučí, a co pro to můžete udělat na svém webu.',
    'answer': 'GEO (generative engine optimization) je optimalizace webu pro AI vyhledávání, tedy pro ChatGPT, Perplexity, Gemini nebo AI odpovědi v Googlu. Aby vás AI doporučila, potřebuje o vás najít jasné, konkrétní a konzistentní informace: srozumitelný web s přímými odpověďmi, strukturovaná data, stejné údaje o firmě napříč internetem a zmínky a recenze na důvěryhodných místech.',
    'takeaways': ['Pište přímé odpovědi na otázky zákazníků', 'Sjednoťte údaje o firmě napříč internetem', 'Pusťte AI roboty na web a sledujte výsledky'],
    'body': [
      ('h2', 'Co je GEO a proč na něm záleží'),
      ('p', 'Klasické SEO řeší, abyste byli vysoko ve výsledcích vyhledávání. GEO řeší, aby vás umělá inteligence zmínila přímo v odpovědi. Když se někdo zeptá „koho doporučuješ na rekonstrukci koupelny v Olomouci?“, AI nevypíše deset odkazů, ale pár konkrétních firem. Kdo v odpovědi není, jako by neexistoval.'),
      ('h2', 'Jak si AI asistenti vybírají zdroje'),
      ('p', 'Asistenti s přístupem k internetu vyhledávají na webu podobně jako vyhledávače a z nalezených stránek skládají odpověď. Přednost dostávají zdroje, které:'),
      ('check', ['odpovídají na otázku jasně a přímo', 'obsahují konkrétní fakta: služby, lokalitu, ceny, postup', 'jsou technicky dostupné, rychlé a dobře strukturované', 'se shodují s tím, co o firmě říkají jiné zdroje', 'mají zmínky a recenze na důvěryhodných místech']),
      ('p', 'Nikdo zvenku neumí zaručit, že vás konkrétní AI doporučí. Dá se ale výrazně zvýšit šance, že vás najde, pochopí a bude vám věřit.'),
      ('h2', 'Co udělat na webu'),
      ('h3', 'Odpověď hned na začátku'),
      ('p', 'Každá důležitá stránka by měla v prvních větách jasně říct, co děláte, pro koho a kde. AI si z textu vybírá krátké, samostatně srozumitelné úseky, takže přímá odpověď má větší šanci být citována než obecné marketingové fráze.'),
      ('h3', 'Otázky a odpovědi'),
      ('p', 'Sekce častých otázek odpovídá přesně na to, na co se lidé AI ptají. Pište je lidsky a konkrétně: kolik to stojí, jak dlouho to trvá, co od zákazníka potřebujete.'),
      ('h3', 'Strukturovaná data'),
      ('p', 'Značky podle schema.org řeknou strojům jednoznačně, kdo jste: název firmy, IČO, kontakty, služby, otázky a odpovědi. Pomáhají vyhledávačům i AI správně pochopit obsah stránky.'),
      ('h3', 'Dostupnost pro AI roboty'),
      ('p', 'V souboru robots.txt nesmí být zablokovaní roboti jako GPTBot, ClaudeBot nebo PerplexityBot, pokud chcete, aby váš obsah znali. Doplňkově se začíná používat soubor llms.txt se shrnutím webu pro AI. Zatím nejde o oficiální standard, ale jeho přidání nic nestojí.'),
      ('cta',),
      ('h2', 'Co udělat mimo web'),
      ('ul', [
        'Sjednoťte název, adresu, telefon a popis firmy na všech místech: Firmy.cz, Firemní profil na Googlu, sociální sítě, katalogy.',
        'Sbírejte skutečné recenze od zákazníků.',
        'Buďte vidět tam, kde se o vašem oboru mluví: oborové weby, články, spolupráce.',
      ]),
      ('tip', 'Jak to změřit', 'Zeptejte se ChatGPT, Perplexity a Gemini na otázky, které kladou vaši zákazníci, a sledujte, jestli vás zmíní. V analytice webu hledejte návštěvy z adres jako chatgpt.com nebo perplexity.ai.'),
      ('h2', 'GEO děláme u každého webu'),
      ('p', 'Každý web od nás je připravený pro AI vyhledávání: přímé odpovědi, otázky a odpovědi, strukturovaná data, povolení AI roboti i llms.txt. Víc o službě najdete na stránce <a href="sluzby/geo/">GEO optimalizace</a>. Základem ale zůstává dobré <a href="sluzby/seo/">SEO</a>, protože AI často čerpá z výsledků klasického vyhledávání.'),
    ],
    'faq': [
      ('Jaký je rozdíl mezi SEO a GEO?', 'SEO se zaměřuje na pozice ve výsledcích vyhledávačů. GEO na to, aby vás AI asistenti zmínili přímo v odpovědi. Obojí stojí na kvalitním, srozumitelném a technicky správném webu, takže se vzájemně doplňují.'),
      ('Může mi někdo zaručit, že mě ChatGPT doporučí?', 'Ne. Odpovědi AI nikdo zvenku neřídí. Správnou přípravou webu a konzistentními informacemi o firmě ale výrazně zvýšíte šanci, že vás AI najde a doporučí.'),
      ('Co je soubor llms.txt?', 'Textový soubor v kořeni webu se stručným shrnutím firmy a důležitých stránek pro jazykové modely. Jde o navrhovaný, zatím neoficiální standard. Jeho přidání je jednoduché a neuškodí.'),
      ('Mám AI roboty na webu blokovat?', 'Pokud chcete, aby vás AI asistenti znali a doporučovali, blokovat je nedává smysl. Blokování zvažte jen u obsahu, který nechcete sdílet.'),
    ],
    'services': ['geo', 'seo'],
  },
  # ------------------------------------------------------------------
  {
    'slug': 'cookie-lista-gdpr-na-webu',
    'cat': 'gdpr', 'obj': 'shield', 'variant': 'bnv-sky', 'read': 7,
    'title': 'Cookie lišta a GDPR na webu: co musí splňovat v roce 2026',
    'desc': 'Co musí splňovat cookie lišta a firemní web podle českých pravidel: souhlas předem, stejně snadné odmítnutí, měřicí kódy až po souhlasu, zásady ochrany osobních údajů.',
    'h1': 'Cookie lišta a GDPR: <span class="serif">co musí web splňovat.</span>',
    'lead': 'Cookie lišta není jen formalita. Ukážeme, co přesně po webech vyžadují česká pravidla, jaké chyby jsou nejčastější a jak mít web v pořádku, aniž byste odradili návštěvníky.',
    'answer': 'Od roku 2022 platí v Česku pro cookies princip předchozího souhlasu: analytické a marketingové cookies a měřicí kódy smí web spustit až poté, co s nimi návštěvník aktivně souhlasí. Odmítnutí musí být stejně snadné jako přijetí, souhlas musí jít kdykoli změnit a web musí mít srozumitelné zásady ochrany osobních údajů. Nezbytné cookies pro fungování webu souhlas nepotřebují.',
    'takeaways': ['Měřicí kódy až po souhlasu', 'Odmítnout musí jít stejně snadno jako přijmout', 'Souhlas musí jít kdykoli změnit'],
    'body': [
      ('h2', 'Co říkají pravidla'),
      ('p', 'Ukládání cookies upravuje v Česku zákon o elektronických komunikacích. Od 1. ledna 2022 vyžaduje pro cookies, které nejsou nezbytné, předchozí souhlas uživatele. Zpracování osobních údajů, třeba z kontaktního formuláře, se řídí nařízením GDPR. Dozor vykonává Úřad pro ochranu osobních údajů.'),
      ('h2', 'Co musí splňovat cookie lišta'),
      ('check', [
        'Volitelné cookies a měřicí kódy se nespustí dřív, než návštěvník souhlasí.',
        'Tlačítko pro odmítnutí je stejně dostupné jako tlačítko pro přijetí.',
        'Žádná předem zaškrtnutá políčka.',
        'Souhlas lze udělit po kategoriích (analytické, marketingové).',
        'Souhlas lze kdykoli změnit nebo odvolat, typicky odkazem v patičce.',
        'Lišta odkazuje na zásady ochrany osobních údajů.',
      ]),
      ('h2', 'Nejčastější chyby'),
      ('ul', [
        'Google Analytics nebo Meta Pixel se načtou hned při otevření stránky, ještě před souhlasem.',
        'Lišta nabízí jen „Souhlasím“ a odmítnutí je schované v nastavení.',
        'Souhlas nejde později změnit.',
        'Zásady ochrany osobních údajů jsou zkopírované z jiného webu a neodpovídají tomu, co web skutečně dělá.',
      ]),
      ('cta',),
      ('h2', 'Kontaktní formulář a osobní údaje'),
      ('p', 'Když formulář sbírá jméno, e-mail nebo telefon, zpracováváte osobní údaje. U formuláře by měla být stručná informace, kdo údaje zpracovává a k čemu, s odkazem na zásady ochrany osobních údajů. Ptejte se jen na to, co opravdu potřebujete.'),
      ('h2', 'Měření a reklama v souladu s pravidly'),
      ('p', 'Měřit návštěvnost a reklamy jde i s cookie lištou. Měřicí kódy se jen musí spouštět podle souhlasu. U Googlu k tomu slouží Consent Mode, který Google pro reklamu v Evropském hospodářském prostoru vyžaduje. Dobře navržená lišta přitom souhlas nevymáhá a web neruší.'),
      ('tip', 'Upozornění', 'Tento článek je obecný přehled, nikoli právní rada. Nastavení vždy záleží na tom, jaké nástroje a služby váš web používá.'),
      ('h2', 'Jak to řešíme my'),
      ('p', 'Každý web od nás má cookie lištu, která spouští měření až po souhlasu, nabízí stejně snadné odmítnutí a umožňuje souhlas kdykoli změnit. Na oblast GDPR spolupracujeme s odborníky z Compliance Partner. Víc na stránce <a href="sluzby/gdpr-cookies/">GDPR a cookies</a>.'),
    ],
    'faq': [
      ('Potřebuje každý web cookie lištu?', 'Lištu potřebuje web, který používá cookies nebo podobné technologie, které nejsou nezbytné pro jeho fungování, typicky analytiku nebo reklamní pixely. Web jen s nezbytnými cookies lištu mít nemusí, ale informace o cookies patří do zásad ochrany osobních údajů.'),
      ('Můžu mít Google Analytics bez souhlasu?', 'Analytické cookies vyžadují předchozí souhlas. Měřicí kód by se tedy měl spustit až po souhlasu návštěvníka.'),
      ('Stačí tlačítko „Souhlasím“?', 'Nestačí. Návštěvník musí mít stejně snadnou možnost souhlas odmítnout a později ho změnit.'),
      ('Kdo kontroluje dodržování pravidel?', 'V Česku Úřad pro ochranu osobních údajů. Za porušení GDPR hrozí pokuty, u nejzávažnějších případů až do výše 20 milionů eur nebo 4 % ročního obratu.'),
    ],
    'services': ['gdpr-cookies', 'tvorba-webu'],
  },
  # ------------------------------------------------------------------
  {
    'slug': 'web-na-miru-nebo-sablona',
    'cat': 'ceny', 'obj': 'cursor', 'variant': 'bnv-sky', 'read': 6,
    'title': 'Web na míru, nebo šablona? Srovnání pro firmy a podnikatele',
    'desc': 'Stavebnice, šablona, nebo web na míru? Srovnání ceny, rychlosti, SEO, designu a vlastnictví. Kdy se které řešení vyplatí a na co si dát pozor.',
    'h1': 'Web na míru, nebo <span class="serif">šablona?</span>',
    'lead': 'Šablona je levná a rychlá, web na míru dražší, ale postavený přesně pro vás. Porovnáme obě cesty i stavebnice a pomůžeme vám vybrat řešení, které se vaší firmě opravdu vyplatí.',
    'answer': 'Šablona nebo stavebnice se hodí pro jednoduchou prezentaci s omezeným rozpočtem. Web na míru se vyplatí, když má web přivádět poptávky nebo prodávat: design i obsah vycházejí z vaší firmy a zákazníků, web bývá rychlejší, lépe optimalizovaný pro vyhledávače a snadněji se rozšiřuje.',
    'takeaways': ['Šablona: rychlá a levná, ale podobná ostatním', 'Na míru: vyšší cena, vyšší výkon a odlišení', 'Rozhodujte podle cíle webu, ne podle ceny'],
    'body': [
      ('h2', 'Tři cesty k firemnímu webu'),
      ('p', '<b>Stavebnice</b> jako Webnode nebo Wix: web si poskládáte sami z hotových bloků. <b>Šablona</b>: hotový vzhled, nejčastěji na WordPressu, do kterého se vloží váš obsah. <b>Web na míru</b>: design, struktura i texty vznikají pro vaši firmu od začátku.'),
      ('table', ['', 'Stavebnice', 'Šablona', 'Na míru'], [
        ['Cena na začátku', 'nejnižší', 'nízká', 'vyšší'],
        ['Rychlost spuštění', 'dny', 'dny až týdny', 'týdny'],
        ['Originalita designu', 'nízká', 'nízká až střední', 'vysoká'],
        ['Rychlost načítání', 'různá', 'často horší kvůli pluginům', 'obvykle nejlepší'],
        ['SEO a GEO', 'omezené', 'záleží na nastavení', 'plná kontrola'],
        ['Rozšiřitelnost', 'omezená', 'střední', 'vysoká'],
        ['Vlastnictví webu', 'u provozovatele', 'vaše', 'vaše'],
      ]),
      ('h2', 'Kdy stačí šablona nebo stavebnice'),
      ('check', ['začínáte a potřebujete jednoduchou vizitku', 'web není hlavní zdroj zákazníků', 'rozpočet je velmi omezený', 'nepotřebujete speciální funkce']),
      ('h2', 'Kdy se vyplatí web na míru'),
      ('check', ['web má přivádět poptávky nebo prodávat', 'chcete se odlišit od konkurence', 'potřebujete rezervace, registrace, e-shop nebo napojení na jiné systémy', 'záleží vám na rychlosti, SEO a přípravě na AI vyhledávání', 'plánujete web rozšiřovat']),
      ('cta',),
      ('h2', 'Skryté náklady šablon'),
      ('p', 'Šablona vypadá levně, ale časem přibývají placené pluginy, licence, aktualizace a opravy po nich. Mnoho funkcí navíc zpomaluje web, a pomalý web ztrácí návštěvníky i pozice. Než se rozhodnete, spočítejte si náklady na dva až tři roky, ne jen cenu spuštění.'),
      ('h2', 'Jak se rozhodnout'),
      ('ol', ['Napište si, co má web přinášet: poptávky, prodej, rezervace.', 'Odhadněte, kolik vám přinese jeden nový zákazník.', 'Porovnejte to s rozdílem v ceně mezi šablonou a webem na míru.', 'Prohlédněte si reference dodavatelů a proklikejte je na mobilu.']),
      ('p', 'Nejjednodušší je vidět rozdíl na vlastní oči. <a href="sluzby/tvorba-webu/">Návrh webu na míru</a> vám připravíme zdarma do 48 hodin a můžete ho porovnat s čímkoli jiným. Inspiraci najdete v <a href="realizace.html">našich realizacích</a>.'),
    ],
    'faq': [
      ('Je web na šabloně špatný?', 'Není. Pro jednoduchou prezentaci může stačit. Omezení se ukážou, když má web přivádět zákazníky, odlišit vás od konkurence nebo růst.'),
      ('O kolik je web na míru dražší než šablona?', 'Obvykle několikanásobně, protože obsahuje víc práce: návrh designu, texty, ladění rychlosti a SEO. Orientační ceny najdete v článku Kolik stojí webové stránky.'),
      ('Můžu později přejít ze šablony na web na míru?', 'Ano. Při přechodu je důležité zachovat obsah, který se daří ve vyhledávání, a přesměrovat staré adresy na nové.'),
    ],
    'services': ['tvorba-webu', 'redesign-webu'],
  },
  # ------------------------------------------------------------------
  {
    'slug': 'uvodni-stranka-ktera-prodava',
    'cat': 'obsah', 'obj': 'check', 'variant': 'bnv-lime', 'read': 7,
    'title': 'Úvodní stránka, která přivádí poptávky: 9 prvků',
    'desc': 'Jak má vypadat úvodní stránka firemního webu, aby z návštěvníků dělala zákazníky. 9 prvků od hlavního sdělení přes reference po jednoduchý formulář.',
    'h1': 'Úvodní stránka, která <span class="serif">přivádí poptávky.</span>',
    'lead': 'Na úvodní stránce se během pár vteřin rozhoduje, jestli návštěvník zůstane. Projdeme devět prvků, díky kterým z návštěvníků vznikají poptávky, a ukážeme je na skutečných příkladech.',
    'answer': 'Úvodní stránka přivádí poptávky, když hned nahoře jasně řekne, co nabízíte a pro koho, ukáže jeden hlavní krok (zavolat, poptat, rezervovat), podpoří ho skutečnými referencemi a výsledky, odpoví na nejčastější obavy a nabídne jednoduchý kontakt, který jde vyplnit za minutu i na mobilu.',
    'takeaways': ['Jasné sdělení v prvních vteřinách', 'Jeden hlavní krok, který chcete po návštěvníkovi', 'Skutečné reference a jednoduchý kontakt'],
    'body': [
      ('h2', '1. Jasné hlavní sdělení'),
      ('p', 'Nadpis má říct, co děláte a proč si vybrat právě vás. Ne „Vítejte na našich stránkách“, ale konkrétní přínos. Srovnejte obecnou větu „Nabízíme kvalitní kovářské a zámečnické práce za příznivé ceny“ s textem, který jsme napsali pro kovárnu <a href="https://kovotuk.cz" target="_blank" rel="noopener">KovoTuk</a>: „Žádná sériová výroba, žádné odlitky.“'),
      ('h2', '2. Jeden hlavní krok'),
      ('p', 'Rozhodněte, co má návštěvník udělat: zavolat, poptat, rezervovat, nebo koupit. Tomuto kroku podřiďte tlačítka na celé stránce. Pět různých výzev návštěvníka mate.'),
      ('h2', '3. Skutečné reference'),
      ('p', 'Loga klientů, ukázky prací a skutečné recenze budují důvěru rychleji než jakýkoli slogan. Vymyšlené recenze naopak důvěru ničí, návštěvníci je poznají.'),
      ('h2', '4. Přínosy, ne vlastnosti'),
      ('p', 'Místo „používáme moderní technologie“ napište, co z toho zákazník má: „web se načte za vteřinu i na mobilu“. Každou vlastnost přeložte do přínosu.'),
      ('h2', '5. Viditelný kontakt'),
      ('p', 'Telefon, e-mail a rychlý kontakt, třeba přes WhatsApp, patří na viditelné místo. Na mobilu pomáhá tlačítko, které je vždy po ruce.'),
      ('cta',),
      ('h2', '6. Odpovědi na obavy'),
      ('p', 'Sekce častých otázek odstraní důvody, proč se lidé neozvou: kolik to stojí, jak dlouho to trvá, co když to nebude fungovat. Navíc pomáhá ve vyhledávání i v odpovědích AI, jak popisujeme v článku o <a href="blog/geo-optimalizace-pro-ai-vyhledavani/">GEO optimalizaci</a>.'),
      ('h2', '7. Rychlost a mobil'),
      ('p', 'Většina návštěvníků dnes přichází z telefonu. Pomalý web nebo drobné písmo na mobilu je nejrychlejší cesta, jak o zákazníka přijít.'),
      ('h2', '8. Důvěryhodnost'),
      ('p', 'Údaje o firmě včetně IČO, srozumitelné zásady ochrany osobních údajů a funkční cookie lišta. Detaily, které návštěvník vědomě nehledá, ale jejich absence ho znejistí.'),
      ('h2', '9. Jednoduchý formulář'),
      ('p', 'Ptejte se jen na to, co opravdu potřebujete. Každé pole navíc snižuje počet odeslaných formulářů. Jméno, e-mail a pár vět obvykle stačí, zbytek doladíte v hovoru.'),
      ('tip', 'Rychlý test', 'Ukažte úvodní stránku na pět vteřin někomu, kdo vaši firmu nezná. Pokud potom neumí říct, co děláte a jak vás kontaktovat, je co zlepšovat.'),
      ('h2', 'Chcete to vidět na svém webu?'),
      ('p', 'Všech devět prvků stavíme do každého webu. Pošlete nám odkaz na současný web a do 48 hodin uvidíte <a href="sluzby/tvorba-webu/">návrh nové úvodní stránky zdarma</a>.'),
    ],
    'faq': [
      ('Co by mělo být na úvodní stránce firemního webu?', 'Jasné sdělení, co nabízíte a pro koho, hlavní výzva k akci, reference, přínosy pro zákazníka, kontakt, odpovědi na časté otázky a jednoduchý formulář.'),
      ('Jak dlouhá má být úvodní stránka?', 'Tak dlouhá, aby odpověděla na hlavní otázky zákazníka. Důležitější než délka je, aby to podstatné bylo hned nahoře a stránka se dobře četla na mobilu.'),
      ('Kolik polí má mít kontaktní formulář?', 'Co nejméně. Obvykle stačí jméno, e-mail nebo telefon a krátká zpráva. Každé pole navíc snižuje počet odeslaných poptávek.'),
    ],
    'services': ['tvorba-webu', 'redesign-webu'],
  },
]
